name: Test and Lint

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/foresight-workflow-kit-action@105a1f2f6eef7e4403adf5592020391ebfc72583 # v1
      if: success() || failure()
      with:
        api_key: ${{ secrets.foresight_api_key }}

    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - name: Use Node.js 24
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - run: npm ci
    - run: npm run test

    - name: Analyze Test and/or Coverage Results
      uses: catchpoint/foresight-test-kit-action@16fcb107ba3a54b63d784ebcc4829b80e0ab79c3 # v1
      if: success() || failure()
      with:
        api_key: ${{ secrets.foresight_api_key }}
        test_format: JUNIT
        test_framework: JEST
        test_path: ./junit.xml
        coverage_format: JACOCO/XML
        coverage_path: ./coverage

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - name: Use Node.js 24
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run format-check
    - run: npm run typecheck
    - run: npm run build
